# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: "Install Python Requirements"
    command: |
      pip install -r requirements.txt
  
  - name: "Install Ubuntu Packages"
    command: |
      sudo apt-get update
      sudo apt-get install -y mysql-client vim wget iputils-ping net-tools netcat-traditional
      # 安装ping
      # sudo apt-get install -y iputils-ping
      # 安装vim
      # sudo apt-get install -y vim
      # 安装wget
      # sudo apt-get install -y wget
      # 安装arp
      # sudo apt-get install -y net-tools
      # 安装nc
      # sudo apt-get -y install netcat-traditional


# # List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
# ports:
#   - port: 3000
#     onOpen: open-preview
